### ISSUE TITLE
Python wrapper of osrm engine

### ISSUE THREAD

**Issue by nilsnolde** [gis-ops/py-osrm#7]
After #6 is merged and probably before we'll write tests (so we don't have to change them after), we should provide a more abstracted usage pattern for the engine, e.g.

```
engine = osrm.Engine("./test_data/ch/monaco")  # or osrm.Actor("./test_data/ch/monaco")

route = engine.route([[1,1],[2,2]], **kwargs)  # kwargs could be abstracted RouteParameters, e.g. for the enums
```

I'm doing that with the Python bindings as well: https://github.com/gis-ops/pyvalhalla/blob/master/valhalla/actor.py. IMO a Python user shouldn't be bothered to know where to import the right enums for. We can abstract everything from here on out in Python and don't need to worry to namespace things in C++ (e.g. RouteAnnotationsType vs TableAnnotationsType). The performance overhead is negligible.

**Comment by nilsnolde** [comment]
Do we even still need this @whytro ?

**Comment by whytro** [comment]
Apologies for the late reply, but probably not, since the current iteration of bindings were adjusted to work without having another Python wrapper layer.
